package aarabdh.ao3integration.util

const val DATE_FORMAT = "yyyy-MM-dd"
const val CSS_END_NOTES = "div.chapter.preface.group > div.end.notes.module > blockquote.userstuff"
const val CSS_START_NOTES = "div.chapter.preface.group > div#notes.notes.module > blockquote.userstuff"
const val CSS_TITLE = "div.chapter.preface.group > h3.title"
const val CSS_CHAPTER = "div.chapter[id^=chapter-]"
const val CSS_SUMMARY = "div.chapter.preface.group > div#summary.summary.module > blockquote.userstuff"
const val CSS_BODY = "div.userstuff.module[role=article]"
const val CSS_COCREATOR = "div.chapter.preface.group > h3.byline"
const val CSS_PUBLISH_DATE = "dl.stats > dd.published"
const val CSS_HEADING = "h3.landmark.heading#work"
const val CSS_CHAPTER_LIST = "ol.chapter.index.group li a[href]"
const val CSS_STORY_ENTRIES = "ol.work.index.group > li"
const val CSS_STORY_LIST_TITLE = "h4.heading > a"
const val CSS_STORY_LIST_SUMMARY = "blockquote.summary"
const val CSS_REQUIRED_TAGS = "ul.required-tags span:not(.text)"
const val CSS_LANGUAGE = "dd.language"
const val CSS_CHAPTER_COUNT = "dd.chapters"
const val CSS_KUDOS = "dd.kudos"
const val CSS_HITS = "dd.hits"
const val CSS_COMMENTS = "dd.comments"
const val CSS_TAGS = "ul.tags.commas"
